site_name: whisper2subtitle
site_url: https://mai0313.github.io/whisper2subtitle/
site_author: Wei Cheng Lee

repo_name: Mai0313/whisper2subtitle
repo_url: https://github.com/Mai0313/whisper2subtitle
edit_uri: edit/master/docs/

docs_dir: docs
site_dir: site
remote_branch: wiki
dev_addr: 0.0.0.0:9987

theme:
  name: material
  font:
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    view: material/eye
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    # primary: teal
    # accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    # primary: teal
    # accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  language: en
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
plugins:
  - search
  - tags
  - blog
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            extensions:
            - griffe_typingdoc
            # General
            # https://mkdocstrings.github.io/python/usage/configuration/general
            allow_inspection: true
            show_bases: true
            show_inheritance_diagram: true
            show_source: true
            # preload_modules:
            #   - openai.types.beta
            find_stubs_package: true

            # Headings
            # https://mkdocstrings.github.io/python/usage/configuration/headings
            heading_level: 2
            parameter_headings: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_object_full_path: false
            show_category_heading: false
            show_symbol_type_heading: false
            show_symbol_type_toc: true

            # Members
            # https://mkdocstrings.github.io/python/usage/configuration/members/
            inherited_members: true
            members_order: source  # source or alphabetical
            filters:
              - "!^_"
              - "!^model_"
            group_by_category: true
            show_submodules: true
            summary:
              attributes: false
              functions: true
              modules: false
            show_labels: false

            # Docs Strings
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings
            docstring_style: google  # google, numpy, sphinx or None
            # See https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html for more info.
            docstring_section_style: table
            merge_init_into_class: true
            relative_crossrefs: true
            ignore_init_summary: true
            trim_doctest_flags: true
            show_if_no_docstring: true
            show_docstring_attributes: true
            show_docstring_functions: true
            show_docstring_classes: true
            show_docstring_modules: true
            show_docstring_description: true
            show_docstring_examples: true
            show_docstring_other_parameters: true
            show_docstring_parameters: true
            show_docstring_raises: true
            show_docstring_receives: true
            show_docstring_returns: true
            show_docstring_warns: true
            show_docstring_yields: true

            # Signatures options
            # https://mkdocstrings.github.io/python/usage/configuration/signatures/
            annotations_path: brief  # brief, source, and full
            line_length: 99
            modernize_annotations: true
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: false
            unwrap_annotated: true

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/Mai0313/whisper2subtitle

  alternate:
  - link: /
    lang: en
    name: en - English
  # - link: /
  #   lang: zh-hant
  #   name: zh-hant - 繁體中文

watch:
  - mkdocs.yml
  - docs

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
