name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Rye
        uses: mai0313/setup-rye@v1.0.3
        with:
          version: 'latest' # Optional, default is latest
          toolchain_version: '3.10' # Optional, default is 3.10
          python_version: '3.10' # Optional, default is 3.10
          use-uv: 'true' # Optional, default is true
          pypi_source: 'https://pypi.org/simple' # Optional

      - name: Deploy docs
        run: |
          rye sync
          rye run gen
